# 03 — Model Training: LegalBERT vs DistilBERT on CUAD

This notebook fine-tunes **two models** on the CUAD commercial-lease clause-extraction task:

| Model | HuggingFace ID | Role |
|---|---|---|
| **LegalBERT** | `nlpaueb/legal-bert-base-uncased` | Primary — pre-trained on legal text |
| **DistilBERT** | `distilbert-base-uncased` | Baseline — smaller, general-purpose BERT |

Both are trained as **extractive QA** models: given a clause-type question and a
contract passage, predict the start/end token positions of the answer span.

### Why chunking is required
Legal contracts have a median of ~7,800 tokens (post-cleaning), well beyond
LegalBERT's 512-token limit.  We use a **sliding-window** approach:
- Window size: `MAX_LENGTH = 384` tokens
- Overlap (stride): `STRIDE = 128` tokens
- For each training row we keep **only the most relevant window** (the one
  containing the answer span for answerable rows, or the first window for
  unanswerable rows), giving roughly 1 training example per data row.

In [1]:
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset
from tqdm.auto import tqdm
from transformers import (
    AutoModelForQuestionAnswering,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
)

# Make src/ importable from within the notebooks/ directory
sys.path.insert(0, str(Path("../src").resolve()))

print(f"PyTorch version : {torch.__version__}")
print(f"MPS available   : {torch.backends.mps.is_available()}")
print(f"CUDA available  : {torch.cuda.is_available()}")

/Users/mustafayunus/Desktop/leaseiq-ml/leaseiq-env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

PyTorch version : 2.12.1
MPS available   : True
CUDA available  : False

In [2]:
# ── File paths ────────────────────────────────────────────────────────────
DATA_PATH      = Path("../data/processed/cuad_final.csv")
MODELS_DIR     = Path("../models")
LEGALBERT_OUT  = MODELS_DIR / "legalbert-cuad"
DISTILBERT_OUT = MODELS_DIR / "distilbert-cuad"

MODELS_DIR.mkdir(parents=True, exist_ok=True)

# ── Model identifiers ─────────────────────────────────────────────────────
LEGALBERT_NAME  = "nlpaueb/legal-bert-base-uncased"
DISTILBERT_NAME = "distilbert-base-uncased"

# ── Tokenisation hyper-parameters ─────────────────────────────────────────
MAX_LENGTH = 384   # token window size; 384 keeps memory manageable on M-series
STRIDE     = 128   # overlap between consecutive windows

# ── Training hyper-parameters ─────────────────────────────────────────────
NUM_TRAIN_CONTRACTS = 50   # contracts from the train split
NUM_EPOCHS          = 2
BATCH_SIZE          = 8
LEARNING_RATE       = 2e-5
WEIGHT_DECAY        = 0.01

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

print("Config:")
print(f"  Training contracts : {NUM_TRAIN_CONTRACTS}")
print(f"  Epochs             : {NUM_EPOCHS}")
print(f"  Batch size         : {BATCH_SIZE}")
print(f"  Max length         : {MAX_LENGTH} tokens")
print(f"  Stride             : {STRIDE} tokens")
print(f"  Learning rate      : {LEARNING_RATE}")

Config:
  Training contracts : 50
  Epochs             : 2
  Batch size         : 8
  Max length         : 384 tokens
  Stride             : 128 tokens
  Learning rate      : 2e-05

## Load and Sample Training Data

In [3]:
df       = pd.read_csv(DATA_PATH)
train_df = df[df["split"] == "train"].reset_index(drop=True)

all_contracts = train_df["contract_id"].unique()
rng           = np.random.default_rng(RANDOM_SEED)
sampled_ids   = rng.choice(all_contracts, size=NUM_TRAIN_CONTRACTS, replace=False)
train_sample  = train_df[train_df["contract_id"].isin(sampled_ids)].reset_index(drop=True)

print(f"Total train contracts available : {len(all_contracts)}")
print(f"Contracts sampled               : {len(sampled_ids)}")
print(f"QA pairs in sample              : {len(train_sample):,}")
print(f"  Answerable                    : {train_sample['is_answerable'].sum():,}")
print(f"  Unanswerable                  : {(~train_sample['is_answerable']).sum():,}")
print(f"Categories covered              : {train_sample[train_sample['is_answerable']]['category'].nunique()} / 41")

Total train contracts available : 408
Contracts sampled               : 50
QA pairs in sample              : 2,729
  Answerable                    : 1,348
  Unanswerable                  : 1,381
Categories covered              : 41 / 41

## Sliding-Window Tokenisation

The `make_qa_examples` function below encodes each (clause-type, contract) pair
into overlapping 384-token windows.  For each training row it returns at most
**one** tokenised example — the chunk most relevant to the answer — instead of
the full ~20 chunks that naive tokenisation would produce.

This is the standard approach used in the SQuAD fine-tuning recipes
(HuggingFace QA tutorial), adapted here for speed on laptop hardware.

In [4]:
def make_qa_examples(df, tokenizer, max_length=384, stride=128,
                     include_token_type_ids=True):
    """
    Convert DataFrame rows into tokenised QA examples (one per row).

    Answerable rows  : keep the first window fully containing the answer span;
                       record exact token start/end positions.
    Unanswerable rows: keep the first window with start=end=0 (CLS convention).

    Args:
        df                    : rows with category, context, answer_text,
                                answer_start, is_answerable columns.
        tokenizer             : HuggingFace tokenizer.
        max_length            : token window size.
        stride                : window overlap in tokens.
        include_token_type_ids: set False for DistilBERT (no token_type_ids).

    Returns:
        List of dicts ready for QADataset.
    """
    examples = []
    skipped  = 0

    for _, row in tqdm(df.iterrows(), total=len(df), desc="tokenising"):
        encoding = tokenizer(
            row["category"],   # question = clause type label
            row["context"],    # context  = contract text
            max_length=max_length,
            truncation="only_second",         # protect question from truncation
            stride=stride,
            return_overflowing_tokens=True,
            return_offsets_mapping=True,
            padding="max_length",
        )

        placed = False
        for chunk_idx in range(len(encoding["input_ids"])):
            seq_ids = encoding.sequence_ids(chunk_idx)
            offsets = encoding["offset_mapping"][chunk_idx]

            # Context token indices within this chunk (sequence_id == 1)
            ctx_tokens = [i for i, s in enumerate(seq_ids) if s == 1]
            if not ctx_tokens:
                continue
            ctx_start, ctx_end = ctx_tokens[0], ctx_tokens[-1]

            # ── Unanswerable: first chunk only, mark as CLS ───────────────
            if not row["is_answerable"]:
                if chunk_idx > 0:
                    continue
                ex = {
                    "input_ids":       encoding["input_ids"][chunk_idx],
                    "attention_mask":  encoding["attention_mask"][chunk_idx],
                    "start_positions": 0,
                    "end_positions":   0,
                }
                if include_token_type_ids and "token_type_ids" in encoding.keys():
                    ex["token_type_ids"] = encoding["token_type_ids"][chunk_idx]
                examples.append(ex)
                placed = True
                break

            # ── Answerable: find the chunk that contains the answer span ──
            a_start = int(row["answer_start"])
            a_end   = a_start + len(str(row["answer_text"])) - 1

            chunk_char_start = offsets[ctx_start][0]
            chunk_char_end   = offsets[ctx_end][1]

            if chunk_char_start > a_start or chunk_char_end < a_end:
                continue  # answer is not in this window; try the next

            # Walk forward to find the start token
            tok_s = ctx_start
            while tok_s <= ctx_end and offsets[tok_s][0] <= a_start:
                tok_s += 1
            tok_s -= 1

            # Walk backward to find the end token
            tok_e = ctx_end
            while tok_e >= ctx_start and offsets[tok_e][1] >= a_end + 1:
                tok_e -= 1
            tok_e += 1

            if tok_s < 0 or tok_e >= max_length or tok_s > tok_e:
                skipped += 1
                continue  # degenerate span; skip

            ex = {
                "input_ids":       encoding["input_ids"][chunk_idx],
                "attention_mask":  encoding["attention_mask"][chunk_idx],
                "start_positions": tok_s,
                "end_positions":   tok_e,
            }
            if include_token_type_ids and "token_type_ids" in encoding.keys():
                ex["token_type_ids"] = encoding["token_type_ids"][chunk_idx]
            examples.append(ex)
            placed = True
            break

        if not placed:
            skipped += 1

    print(f"Examples created : {len(examples):,}  |  skipped : {skipped}")
    return examples

In [5]:
class QADataset(Dataset):
    """
    Minimal PyTorch Dataset wrapper around the list of tokenised QA examples.
    Each example dict is converted to long tensors on __getitem__.
    """

    def __init__(self, examples):
        self.examples = examples

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        return {k: torch.tensor(v, dtype=torch.long)
                for k, v in self.examples[idx].items()}

## Fine-tune LegalBERT

LegalBERT was pre-trained on 12 GB of legal text (contracts, case law, legislation).
Its domain vocabulary makes it the expected top performer on CUAD.  We add a
randomly-initialised QA head (`BertForQuestionAnswering`) and fine-tune end-to-end.

In [6]:
print(f"Loading LegalBERT tokenizer from: {LEGALBERT_NAME}")
lb_tokenizer = AutoTokenizer.from_pretrained(LEGALBERT_NAME)
print("Done.")

Loading LegalBERT tokenizer from: nlpaueb/legal-bert-base-uncased

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Done.

In [7]:
print("Tokenising training sample for LegalBERT...")
lb_examples = make_qa_examples(
    train_sample, lb_tokenizer,
    max_length=MAX_LENGTH,
    stride=STRIDE,
    include_token_type_ids=True,   # BERT-based models use token_type_ids
)
lb_train_ds = QADataset(lb_examples)
print(f"LegalBERT training dataset: {len(lb_train_ds):,} examples")

Tokenising training sample for LegalBERT...

tokenising:   0%|          | 0/2729 [00:00<?, ?it/s]

tokenising:   0%|          | 3/2729 [00:00<01:36, 28.25it/s]

tokenising:   0%|          | 9/2729 [00:00<01:01, 43.95it/s]

tokenising:   1%|          | 15/2729 [00:00<00:55, 48.65it/s]

tokenising:   1%|          | 21/2729 [00:00<00:52, 51.18it/s]

tokenising:   1%|          | 27/2729 [00:00<00:51, 52.56it/s]

tokenising:   1%|          | 33/2729 [00:00<00:50, 53.17it/s]

tokenising:   1%|▏         | 39/2729 [00:00<00:50, 53.54it/s]

tokenising:   2%|▏         | 45/2729 [00:00<00:50, 53.46it/s]

tokenising:   2%|▏         | 51/2729 [00:00<00:49, 53.60it/s]

tokenising:   2%|▏         | 57/2729 [00:01<00:49, 53.86it/s]

tokenising:   2%|▏         | 63/2729 [00:01<00:49, 53.80it/s]

tokenising:   3%|▎         | 69/2729 [00:01<00:49, 53.68it/s]

tokenising:   3%|▎         | 75/2729 [00:01<00:55, 47.95it/s]

tokenising:   3%|▎         | 89/2729 [00:01<00:37, 70.64it/s]

tokenising:   4%|▍         | 103/2729 [00:01<00:29, 88.06it/s]

tokenising:   4%|▍         | 117/2729 [00:01<00:25, 100.90it/s]

tokenising:   5%|▍         | 128/2729 [00:02<01:00, 43.25it/s]

tokenising:   5%|▍         | 136/2729 [00:02<01:23, 31.21it/s]

tokenising:   5%|▌         | 143/2729 [00:03<01:38, 26.16it/s]

tokenising:   5%|▌         | 148/2729 [00:03<01:49, 23.60it/s]

tokenising:   6%|▌         | 152/2729 [00:03<02:02, 21.10it/s]

tokenising:   6%|▌         | 156/2729 [00:04<02:08, 20.02it/s]

tokenising:   6%|▌         | 159/2729 [00:04<02:12, 19.46it/s]

tokenising:   6%|▌         | 162/2729 [00:04<02:15, 18.93it/s]

tokenising:   6%|▌         | 165/2729 [00:04<02:18, 18.50it/s]

tokenising:   6%|▌         | 168/2729 [00:04<02:21, 18.09it/s]

tokenising:   6%|▌         | 170/2729 [00:04<02:22, 17.96it/s]

tokenising:   6%|▋         | 172/2729 [00:05<02:24, 17.64it/s]

tokenising:   6%|▋         | 174/2729 [00:05<02:27, 17.38it/s]

tokenising:   6%|▋         | 176/2729 [00:05<02:27, 17.26it/s]

tokenising:   7%|▋         | 178/2729 [00:05<02:29, 17.05it/s]

tokenising:   7%|▋         | 180/2729 [00:05<02:29, 17.01it/s]

tokenising:   7%|▋         | 182/2729 [00:05<02:29, 17.07it/s]

tokenising:   7%|▋         | 184/2729 [00:05<02:30, 16.95it/s]

tokenising:   7%|▋         | 186/2729 [00:05<02:30, 16.91it/s]

tokenising:   7%|▋         | 188/2729 [00:06<02:28, 17.11it/s]

tokenising:   7%|▋         | 191/2729 [00:06<02:13, 19.04it/s]

tokenising:   7%|▋         | 194/2729 [00:06<02:05, 20.21it/s]

tokenising:   7%|▋         | 197/2729 [00:06<01:59, 21.20it/s]

tokenising:   7%|▋         | 200/2729 [00:06<01:56, 21.74it/s]

tokenising:   7%|▋         | 203/2729 [00:06<01:54, 22.10it/s]

tokenising:   8%|▊         | 206/2729 [00:06<01:52, 22.52it/s]

tokenising:   8%|▊         | 209/2729 [00:06<01:51, 22.56it/s]

tokenising:   8%|▊         | 212/2729 [00:07<01:50, 22.78it/s]

tokenising:   8%|▊         | 215/2729 [00:07<01:49, 22.91it/s]

tokenising:   8%|▊         | 218/2729 [00:07<01:49, 22.98it/s]

tokenising:   8%|▊         | 221/2729 [00:07<01:50, 22.68it/s]

tokenising:   8%|▊         | 224/2729 [00:07<01:51, 22.43it/s]

tokenising:   8%|▊         | 227/2729 [00:07<01:51, 22.38it/s]

tokenising:   8%|▊         | 230/2729 [00:07<01:51, 22.49it/s]

tokenising:   9%|▊         | 233/2729 [00:07<01:50, 22.58it/s]

tokenising:   9%|▊         | 236/2729 [00:08<01:50, 22.55it/s]

tokenising:   9%|▉         | 239/2729 [00:08<01:51, 22.42it/s]

tokenising:   9%|▉         | 242/2729 [00:08<01:43, 24.12it/s]

tokenising:   9%|▉         | 250/2729 [00:08<01:04, 38.24it/s]

tokenising:   9%|▉         | 258/2729 [00:08<00:50, 49.17it/s]

tokenising:  10%|▉         | 266/2729 [00:08<00:43, 57.22it/s]

tokenising:  10%|█         | 274/2729 [00:08<00:38, 63.23it/s]

tokenising:  10%|█         | 282/2729 [00:08<00:36, 67.41it/s]

tokenising:  11%|█         | 290/2729 [00:08<00:34, 70.65it/s]

tokenising:  13%|█▎        | 342/2729 [00:09<00:11, 199.09it/s]

tokenising:  13%|█▎        | 363/2729 [00:09<00:12, 190.23it/s]

tokenising:  14%|█▍        | 383/2729 [00:09<00:12, 185.38it/s]

tokenising:  15%|█▍        | 402/2729 [00:09<00:18, 126.57it/s]

tokenising:  15%|█▌        | 418/2729 [00:09<00:21, 106.97it/s]

tokenising:  16%|█▌        | 431/2729 [00:09<00:23, 96.71it/s]

tokenising:  16%|█▌        | 443/2729 [00:10<00:31, 71.58it/s]

tokenising:  17%|█▋        | 452/2729 [00:10<00:37, 60.35it/s]

tokenising:  17%|█▋        | 460/2729 [00:10<00:42, 53.30it/s]

tokenising:  17%|█▋        | 467/2729 [00:10<00:46, 48.71it/s]

tokenising:  17%|█▋        | 473/2729 [00:11<00:49, 45.71it/s]

tokenising:  18%|█▊        | 478/2729 [00:11<00:51, 43.72it/s]

tokenising:  18%|█▊        | 483/2729 [00:11<00:53, 42.09it/s]

tokenising:  18%|█▊        | 488/2729 [00:11<00:54, 40.85it/s]

tokenising:  18%|█▊        | 493/2729 [00:11<00:56, 39.65it/s]

tokenising:  18%|█▊        | 502/2729 [00:11<00:44, 50.58it/s]

tokenising:  19%|█▊        | 511/2729 [00:11<00:37, 59.69it/s]

tokenising:  19%|█▉        | 520/2729 [00:11<00:33, 66.70it/s]

tokenising:  19%|█▉        | 529/2729 [00:12<00:30, 72.02it/s]

tokenising:  20%|█▉        | 538/2729 [00:12<00:28, 76.19it/s]

tokenising:  20%|██        | 550/2729 [00:12<00:24, 87.70it/s]

tokenising:  21%|██        | 566/2729 [00:12<00:20, 106.22it/s]

tokenising:  21%|██▏       | 582/2729 [00:12<00:17, 119.79it/s]

tokenising:  22%|██▏       | 596/2729 [00:12<00:17, 121.94it/s]

tokenising:  22%|██▏       | 609/2729 [00:12<00:22, 93.82it/s]

tokenising:  23%|██▎       | 620/2729 [00:12<00:25, 83.14it/s]

tokenising:  23%|██▎       | 630/2729 [00:13<00:27, 77.05it/s]

tokenising:  23%|██▎       | 639/2729 [00:13<00:28, 73.53it/s]

tokenising:  24%|██▎       | 647/2729 [00:13<00:28, 74.00it/s]

tokenising:  24%|██▍       | 664/2729 [00:13<00:21, 96.89it/s]

tokenising:  25%|██▍       | 681/2729 [00:13<00:17, 115.18it/s]

tokenising:  25%|██▌       | 694/2729 [00:13<00:20, 99.59it/s]

tokenising:  26%|██▌       | 705/2729 [00:14<00:28, 70.96it/s]

tokenising:  26%|██▌       | 714/2729 [00:14<00:33, 59.57it/s]

tokenising:  26%|██▋       | 722/2729 [00:14<00:42, 47.33it/s]

tokenising:  27%|██▋       | 728/2729 [00:14<00:44, 45.27it/s]

tokenising:  27%|██▋       | 734/2729 [00:14<00:45, 43.51it/s]

tokenising:  27%|██▋       | 739/2729 [00:14<00:47, 42.28it/s]

tokenising:  27%|██▋       | 744/2729 [00:15<00:47, 41.39it/s]

tokenising:  28%|██▊       | 756/2729 [00:15<00:34, 57.56it/s]

tokenising:  28%|██▊       | 771/2729 [00:15<00:25, 77.79it/s]

tokenising:  29%|██▉       | 786/2729 [00:15<00:20, 94.29it/s]

tokenising:  29%|██▉       | 797/2729 [00:16<00:52, 36.77it/s]

tokenising:  29%|██▉       | 805/2729 [00:17<01:40, 19.06it/s]

tokenising:  30%|██▉       | 811/2729 [00:18<02:12, 14.46it/s]

tokenising:  30%|██▉       | 816/2729 [00:18<02:38, 12.10it/s]

tokenising:  30%|███       | 820/2729 [00:19<02:56, 10.80it/s]

tokenising:  30%|███       | 823/2729 [00:19<03:11,  9.94it/s]

tokenising:  30%|███       | 825/2729 [00:20<03:21,  9.44it/s]

tokenising:  30%|███       | 827/2729 [00:20<03:31,  9.01it/s]

tokenising:  30%|███       | 829/2729 [00:20<03:39,  8.66it/s]

tokenising:  30%|███       | 831/2729 [00:20<03:45,  8.41it/s]

tokenising:  31%|███       | 833/2729 [00:21<03:53,  8.13it/s]

tokenising:  31%|███       | 834/2729 [00:21<03:57,  7.98it/s]

tokenising:  31%|███       | 835/2729 [00:21<04:00,  7.89it/s]

tokenising:  31%|███       | 836/2729 [00:21<04:03,  7.79it/s]

tokenising:  31%|███       | 837/2729 [00:21<04:06,  7.69it/s]

tokenising:  31%|███       | 838/2729 [00:21<04:09,  7.57it/s]

tokenising:  31%|███       | 839/2729 [00:21<04:11,  7.51it/s]

tokenising:  31%|███       | 840/2729 [00:22<04:10,  7.54it/s]

tokenising:  31%|███       | 841/2729 [00:22<04:13,  7.44it/s]

tokenising:  31%|███       | 842/2729 [00:22<04:17,  7.33it/s]

tokenising:  31%|███       | 843/2729 [00:22<04:20,  7.25it/s]

tokenising:  31%|███       | 844/2729 [00:22<04:21,  7.20it/s]

tokenising:  31%|███       | 845/2729 [00:22<04:27,  7.05it/s]

tokenising:  31%|███       | 846/2729 [00:22<04:26,  7.06it/s]

tokenising:  31%|███       | 847/2729 [00:23<04:23,  7.13it/s]

tokenising:  31%|███       | 848/2729 [00:23<04:42,  6.65it/s]

tokenising:  31%|███       | 849/2729 [00:23<04:49,  6.48it/s]

tokenising:  31%|███       | 850/2729 [00:23<04:50,  6.47it/s]

tokenising:  31%|███       | 851/2729 [00:23<04:40,  6.70it/s]

tokenising:  31%|███       | 852/2729 [00:23<04:35,  6.82it/s]

tokenising:  31%|███▏      | 853/2729 [00:23<04:28,  6.99it/s]

tokenising:  31%|███▏      | 854/2729 [00:24<04:26,  7.05it/s]

tokenising:  31%|███▏      | 855/2729 [00:24<04:26,  7.03it/s]

tokenising:  31%|███▏      | 856/2729 [00:24<04:25,  7.06it/s]

tokenising:  31%|███▏      | 857/2729 [00:24<04:23,  7.12it/s]

tokenising:  31%|███▏      | 858/2729 [00:24<04:26,  7.03it/s]

tokenising:  31%|███▏      | 859/2729 [00:24<04:24,  7.06it/s]

tokenising:  32%|███▏      | 860/2729 [00:24<04:25,  7.04it/s]

tokenising:  32%|███▏      | 861/2729 [00:25<04:23,  7.09it/s]

tokenising:  32%|███▏      | 862/2729 [00:25<04:23,  7.08it/s]

tokenising:  32%|███▏      | 863/2729 [00:25<04:22,  7.12it/s]

tokenising:  32%|███▏      | 864/2729 [00:25<04:22,  7.09it/s]

tokenising:  32%|███▏      | 865/2729 [00:25<04:20,  7.16it/s]

tokenising:  32%|███▏      | 866/2729 [00:25<04:18,  7.20it/s]

tokenising:  32%|███▏      | 867/2729 [00:25<04:18,  7.20it/s]

tokenising:  32%|███▏      | 868/2729 [00:26<04:14,  7.30it/s]

tokenising:  32%|███▏      | 869/2729 [00:26<04:13,  7.35it/s]

tokenising:  32%|███▏      | 870/2729 [00:26<04:14,  7.29it/s]

tokenising:  32%|███▏      | 871/2729 [00:26<04:12,  7.37it/s]

tokenising:  32%|███▏      | 872/2729 [00:26<04:12,  7.36it/s]

tokenising:  32%|███▏      | 873/2729 [00:26<04:13,  7.31it/s]

tokenising:  32%|███▏      | 874/2729 [00:26<04:15,  7.26it/s]

tokenising:  32%|███▏      | 875/2729 [00:27<04:18,  7.17it/s]

tokenising:  32%|███▏      | 876/2729 [00:27<04:22,  7.05it/s]

tokenising:  32%|███▏      | 877/2729 [00:27<04:19,  7.13it/s]

tokenising:  32%|███▏      | 878/2729 [00:27<04:21,  7.08it/s]

tokenising:  32%|███▏      | 879/2729 [00:27<04:19,  7.14it/s]

tokenising:  32%|███▏      | 880/2729 [00:27<04:15,  7.23it/s]

tokenising:  32%|███▏      | 881/2729 [00:27<04:14,  7.27it/s]

tokenising:  33%|███▎      | 888/2729 [00:27<01:23, 22.12it/s]

tokenising:  33%|███▎      | 896/2729 [00:28<00:50, 36.18it/s]

tokenising:  33%|███▎      | 904/2729 [00:28<00:38, 46.92it/s]

tokenising:  33%|███▎      | 912/2729 [00:28<00:33, 54.95it/s]

tokenising:  34%|███▎      | 919/2729 [00:28<00:35, 50.46it/s]

tokenising:  34%|███▍      | 927/2729 [00:28<00:31, 56.98it/s]

tokenising:  34%|███▍      | 936/2729 [00:28<00:27, 65.29it/s]

tokenising:  35%|███▍      | 945/2729 [00:28<00:24, 71.62it/s]

tokenising:  35%|███▍      | 954/2729 [00:28<00:23, 76.29it/s]

tokenising:  35%|███▌      | 963/2729 [00:28<00:22, 79.83it/s]

tokenising:  36%|███▌      | 972/2729 [00:29<00:21, 82.33it/s]

tokenising:  36%|███▌      | 984/2729 [00:29<00:18, 92.45it/s]

tokenising:  37%|███▋      | 999/2729 [00:29<00:15, 109.12it/s]

tokenising:  37%|███▋      | 1015/2729 [00:29<00:14, 121.82it/s]

tokenising:  38%|███▊      | 1030/2729 [00:29<00:13, 130.01it/s]

tokenising:  38%|███▊      | 1044/2729 [00:29<00:12, 129.86it/s]

tokenising:  39%|███▉      | 1058/2729 [00:29<00:13, 125.19it/s]

tokenising:  39%|███▉      | 1071/2729 [00:29<00:13, 121.95it/s]

tokenising:  40%|███▉      | 1084/2729 [00:29<00:13, 122.33it/s]

tokenising:  42%|████▏     | 1136/2729 [00:30<00:06, 230.65it/s]

tokenising:  43%|████▎     | 1160/2729 [00:30<00:16, 92.57it/s]

tokenising:  43%|████▎     | 1178/2729 [00:31<00:22, 68.79it/s]

tokenising:  44%|████▎     | 1192/2729 [00:31<00:25, 60.56it/s]

tokenising:  44%|████▍     | 1208/2729 [00:31<00:21, 71.69it/s]

tokenising:  45%|████▍     | 1224/2729 [00:31<00:17, 83.62it/s]

tokenising:  45%|████▌     | 1239/2729 [00:31<00:15, 93.66it/s]

tokenising:  46%|████▌     | 1255/2729 [00:31<00:13, 105.48it/s]

tokenising:  47%|████▋     | 1271/2729 [00:32<00:12, 116.15it/s]

tokenising:  47%|████▋     | 1287/2729 [00:32<00:11, 125.75it/s]

tokenising:  48%|████▊     | 1302/2729 [00:32<00:10, 130.70it/s]

tokenising:  48%|████▊     | 1317/2729 [00:32<00:11, 128.32it/s]

tokenising:  49%|████▉     | 1331/2729 [00:32<00:11, 126.70it/s]

tokenising:  49%|████▉     | 1345/2729 [00:32<00:10, 126.00it/s]

tokenising:  50%|████▉     | 1359/2729 [00:32<00:11, 123.71it/s]

tokenising:  50%|█████     | 1372/2729 [00:32<00:11, 119.31it/s]

tokenising:  51%|█████     | 1385/2729 [00:32<00:11, 115.74it/s]

tokenising:  51%|█████     | 1397/2729 [00:33<00:11, 114.47it/s]

tokenising:  52%|█████▏    | 1409/2729 [00:33<00:13, 95.24it/s]

tokenising:  52%|█████▏    | 1420/2729 [00:33<00:16, 77.75it/s]

tokenising:  52%|█████▏    | 1429/2729 [00:33<00:18, 69.43it/s]

tokenising:  53%|█████▎    | 1437/2729 [00:33<00:20, 64.47it/s]

tokenising:  53%|█████▎    | 1444/2729 [00:33<00:22, 58.21it/s]

tokenising:  53%|█████▎    | 1451/2729 [00:34<00:22, 56.11it/s]

tokenising:  53%|█████▎    | 1457/2729 [00:34<00:23, 54.85it/s]

tokenising:  54%|█████▎    | 1463/2729 [00:34<00:23, 53.94it/s]

tokenising:  54%|█████▍    | 1470/2729 [00:34<00:21, 57.81it/s]

tokenising:  55%|█████▌    | 1513/2729 [00:34<00:08, 148.25it/s]

tokenising:  56%|█████▌    | 1529/2729 [00:35<00:20, 58.14it/s]

tokenising:  56%|█████▋    | 1541/2729 [00:35<00:28, 42.08it/s]

tokenising:  57%|█████▋    | 1550/2729 [00:36<00:33, 35.46it/s]

tokenising:  57%|█████▋    | 1557/2729 [00:36<00:36, 31.95it/s]

tokenising:  57%|█████▋    | 1563/2729 [00:36<00:39, 29.57it/s]

tokenising:  57%|█████▋    | 1568/2729 [00:37<00:41, 27.90it/s]

tokenising:  58%|█████▊    | 1572/2729 [00:37<00:43, 26.89it/s]

tokenising:  58%|█████▊    | 1576/2729 [00:37<00:42, 26.82it/s]

tokenising:  58%|█████▊    | 1584/2729 [00:37<00:33, 34.58it/s]

tokenising:  58%|█████▊    | 1592/2729 [00:37<00:27, 41.77it/s]

tokenising:  59%|█████▊    | 1600/2729 [00:37<00:23, 48.37it/s]

tokenising:  59%|█████▉    | 1608/2729 [00:37<00:20, 53.95it/s]

tokenising:  59%|█████▉    | 1616/2729 [00:37<00:18, 58.76it/s]

tokenising:  60%|█████▉    | 1624/2729 [00:37<00:17, 62.36it/s]

tokenising:  60%|█████▉    | 1631/2729 [00:38<00:23, 47.38it/s]

tokenising:  60%|█████▉    | 1637/2729 [00:38<00:27, 39.51it/s]

tokenising:  60%|██████    | 1642/2729 [00:38<00:30, 35.57it/s]

tokenising:  60%|██████    | 1647/2729 [00:38<00:32, 32.85it/s]

tokenising:  60%|██████    | 1651/2729 [00:38<00:34, 31.20it/s]

tokenising:  61%|██████    | 1655/2729 [00:39<00:35, 29.95it/s]

tokenising:  61%|██████    | 1659/2729 [00:39<00:37, 28.63it/s]

tokenising:  61%|██████    | 1662/2729 [00:39<00:38, 28.02it/s]

tokenising:  61%|██████    | 1665/2729 [00:39<00:38, 27.80it/s]

tokenising:  61%|██████    | 1668/2729 [00:39<00:39, 27.15it/s]

tokenising:  61%|██████    | 1671/2729 [00:39<00:39, 26.65it/s]

tokenising:  61%|██████▏   | 1674/2729 [00:39<00:39, 26.43it/s]

tokenising:  61%|██████▏   | 1677/2729 [00:39<00:39, 26.51it/s]

tokenising:  62%|██████▏   | 1680/2729 [00:40<00:39, 26.78it/s]

tokenising:  62%|██████▏   | 1683/2729 [00:40<00:39, 26.81it/s]

tokenising:  62%|██████▏   | 1686/2729 [00:40<00:39, 26.69it/s]

tokenising:  62%|██████▏   | 1689/2729 [00:40<00:39, 26.60it/s]

tokenising:  62%|██████▏   | 1692/2729 [00:40<00:39, 26.13it/s]

tokenising:  62%|██████▏   | 1695/2729 [00:40<00:39, 26.35it/s]

tokenising:  62%|██████▏   | 1698/2729 [00:40<00:39, 26.01it/s]

tokenising:  62%|██████▏   | 1701/2729 [00:40<00:39, 25.97it/s]

tokenising:  62%|██████▏   | 1704/2729 [00:41<00:39, 26.04it/s]

tokenising:  63%|██████▎   | 1707/2729 [00:41<00:38, 26.21it/s]

tokenising:  63%|██████▎   | 1710/2729 [00:41<00:46, 22.04it/s]

tokenising:  63%|██████▎   | 1713/2729 [00:41<00:43, 23.35it/s]

tokenising:  63%|██████▎   | 1716/2729 [00:41<00:41, 24.33it/s]

tokenising:  63%|██████▎   | 1719/2729 [00:41<00:40, 24.98it/s]

tokenising:  63%|██████▎   | 1722/2729 [00:41<00:40, 25.04it/s]

tokenising:  63%|██████▎   | 1725/2729 [00:41<00:39, 25.46it/s]

tokenising:  63%|██████▎   | 1728/2729 [00:41<00:37, 26.55it/s]

tokenising:  63%|██████▎   | 1732/2729 [00:42<00:33, 29.78it/s]

tokenising:  64%|██████▎   | 1736/2729 [00:42<00:30, 32.23it/s]

tokenising:  64%|██████▍   | 1740/2729 [00:42<00:29, 33.90it/s]

tokenising:  64%|██████▍   | 1744/2729 [00:42<00:28, 34.87it/s]

tokenising:  64%|██████▍   | 1748/2729 [00:42<00:27, 35.66it/s]

tokenising:  64%|██████▍   | 1752/2729 [00:42<00:27, 36.15it/s]

tokenising:  64%|██████▍   | 1756/2729 [00:42<00:26, 36.49it/s]

tokenising:  64%|██████▍   | 1760/2729 [00:42<00:26, 36.68it/s]

tokenising:  65%|██████▍   | 1764/2729 [00:42<00:26, 36.79it/s]

tokenising:  65%|██████▍   | 1768/2729 [00:43<00:26, 36.93it/s]

tokenising:  65%|██████▍   | 1772/2729 [00:43<00:25, 37.07it/s]

tokenising:  65%|██████▌   | 1776/2729 [00:43<00:25, 37.07it/s]

tokenising:  65%|██████▌   | 1780/2729 [00:43<00:25, 37.20it/s]

tokenising:  65%|██████▌   | 1784/2729 [00:43<00:25, 37.20it/s]

tokenising:  66%|██████▌   | 1788/2729 [00:43<00:25, 37.23it/s]

tokenising:  66%|██████▌   | 1792/2729 [00:43<00:25, 37.36it/s]

tokenising:  66%|██████▌   | 1796/2729 [00:43<00:25, 37.11it/s]

tokenising:  66%|██████▌   | 1800/2729 [00:43<00:25, 36.96it/s]

tokenising:  66%|██████▌   | 1806/2729 [00:44<00:21, 42.04it/s]

tokenising:  66%|██████▋   | 1812/2729 [00:44<00:19, 47.08it/s]

tokenising:  67%|██████▋   | 1817/2729 [00:44<00:20, 45.55it/s]

tokenising:  67%|██████▋   | 1822/2729 [00:44<00:20, 43.25it/s]

tokenising:  67%|██████▋   | 1829/2729 [00:44<00:18, 49.46it/s]

tokenising:  67%|██████▋   | 1836/2729 [00:44<00:16, 54.78it/s]

tokenising:  68%|██████▊   | 1843/2729 [00:44<00:15, 58.17it/s]

tokenising:  68%|██████▊   | 1850/2729 [00:44<00:14, 60.76it/s]

tokenising:  68%|██████▊   | 1857/2729 [00:45<00:18, 48.30it/s]

tokenising:  68%|██████▊   | 1863/2729 [00:45<00:22, 38.04it/s]

tokenising:  68%|██████▊   | 1868/2729 [00:45<00:25, 34.05it/s]

tokenising:  69%|██████▊   | 1872/2729 [00:45<00:26, 32.41it/s]

tokenising:  69%|██████▊   | 1876/2729 [00:45<00:27, 30.93it/s]

tokenising:  69%|██████▉   | 1880/2729 [00:45<00:28, 29.97it/s]

tokenising:  69%|██████▉   | 1884/2729 [00:46<00:28, 29.25it/s]

tokenising:  69%|██████▉   | 1888/2729 [00:46<00:29, 28.89it/s]

tokenising:  69%|██████▉   | 1891/2729 [00:46<00:29, 28.74it/s]

tokenising:  69%|██████▉   | 1894/2729 [00:46<00:29, 28.65it/s]

tokenising:  70%|██████▉   | 1897/2729 [00:46<00:29, 28.38it/s]

tokenising:  70%|██████▉   | 1900/2729 [00:46<00:29, 28.05it/s]

tokenising:  70%|██████▉   | 1903/2729 [00:46<00:29, 27.88it/s]

tokenising:  70%|██████▉   | 1906/2729 [00:46<00:29, 27.81it/s]

tokenising:  70%|██████▉   | 1909/2729 [00:46<00:29, 27.74it/s]

tokenising:  70%|███████   | 1912/2729 [00:47<00:29, 27.89it/s]

tokenising:  70%|███████   | 1915/2729 [00:47<00:29, 28.02it/s]

tokenising:  70%|███████   | 1918/2729 [00:47<00:28, 28.09it/s]

tokenising:  70%|███████   | 1921/2729 [00:47<00:28, 27.92it/s]

tokenising:  71%|███████   | 1924/2729 [00:47<00:28, 27.85it/s]

tokenising:  71%|███████   | 1931/2729 [00:47<00:20, 38.63it/s]

tokenising:  71%|███████   | 1938/2729 [00:47<00:17, 46.17it/s]

tokenising:  71%|███████▏  | 1945/2729 [00:47<00:15, 51.50it/s]

tokenising:  72%|███████▏  | 1952/2729 [00:47<00:14, 55.16it/s]

tokenising:  72%|███████▏  | 1959/2729 [00:48<00:13, 58.12it/s]

tokenising:  72%|███████▏  | 1966/2729 [00:48<00:12, 60.50it/s]

tokenising:  72%|███████▏  | 1975/2729 [00:48<00:10, 68.88it/s]

tokenising:  73%|███████▎  | 1994/2729 [00:48<00:07, 102.66it/s]

tokenising:  74%|███████▎  | 2012/2729 [00:48<00:05, 124.25it/s]

tokenising:  74%|███████▍  | 2025/2729 [00:48<00:05, 118.76it/s]

tokenising:  75%|███████▍  | 2037/2729 [00:48<00:06, 100.24it/s]

tokenising:  75%|███████▌  | 2048/2729 [00:48<00:07, 90.29it/s]

tokenising:  75%|███████▌  | 2058/2729 [00:49<00:07, 84.78it/s]

tokenising:  76%|███████▌  | 2067/2729 [00:49<00:08, 81.46it/s]

tokenising:  76%|███████▌  | 2076/2729 [00:49<00:08, 78.30it/s]

tokenising:  76%|███████▋  | 2084/2729 [00:49<00:08, 73.69it/s]

tokenising:  77%|███████▋  | 2092/2729 [00:49<00:09, 70.38it/s]

tokenising:  77%|███████▋  | 2100/2729 [00:49<00:09, 67.87it/s]

tokenising:  77%|███████▋  | 2107/2729 [00:49<00:09, 66.33it/s]

tokenising:  77%|███████▋  | 2114/2729 [00:49<00:09, 64.70it/s]

tokenising:  78%|███████▊  | 2121/2729 [00:49<00:09, 63.57it/s]

tokenising:  78%|███████▊  | 2137/2729 [00:50<00:06, 88.44it/s]

tokenising:  79%|███████▉  | 2162/2729 [00:50<00:04, 132.40it/s]

tokenising:  80%|███████▉  | 2176/2729 [00:50<00:04, 122.35it/s]

tokenising:  80%|████████  | 2189/2729 [00:50<00:05, 92.53it/s]

tokenising:  81%|████████  | 2200/2729 [00:50<00:06, 79.93it/s]

tokenising:  81%|████████  | 2210/2729 [00:50<00:07, 72.54it/s]

tokenising:  81%|████████▏ | 2219/2729 [00:51<00:07, 68.97it/s]

tokenising:  82%|████████▏ | 2227/2729 [00:51<00:07, 68.99it/s]

tokenising:  82%|████████▏ | 2235/2729 [00:51<00:07, 68.69it/s]

tokenising:  82%|████████▏ | 2243/2729 [00:51<00:07, 68.82it/s]

tokenising:  82%|████████▏ | 2251/2729 [00:51<00:06, 68.75it/s]

tokenising:  83%|████████▎ | 2259/2729 [00:51<00:06, 68.85it/s]

tokenising:  83%|████████▎ | 2266/2729 [00:51<00:06, 68.18it/s]

tokenising:  83%|████████▎ | 2273/2729 [00:51<00:06, 68.17it/s]

tokenising:  84%|████████▎ | 2280/2729 [00:51<00:06, 68.12it/s]

tokenising:  84%|████████▍ | 2302/2729 [00:52<00:03, 109.51it/s]

tokenising:  85%|████████▌ | 2327/2729 [00:52<00:02, 148.33it/s]

tokenising:  86%|████████▌ | 2343/2729 [00:52<00:03, 124.60it/s]

tokenising:  86%|████████▋ | 2357/2729 [00:52<00:03, 111.51it/s]

tokenising:  87%|████████▋ | 2369/2729 [00:52<00:03, 103.55it/s]

tokenising:  87%|████████▋ | 2380/2729 [00:52<00:03, 102.00it/s]

tokenising:  88%|████████▊ | 2403/2729 [00:52<00:02, 132.39it/s]

tokenising:  89%|████████▉ | 2423/2729 [00:52<00:02, 149.29it/s]

tokenising:  89%|████████▉ | 2439/2729 [00:53<00:03, 83.96it/s]

tokenising:  90%|████████▉ | 2452/2729 [00:53<00:04, 57.85it/s]

tokenising:  90%|█████████ | 2462/2729 [00:54<00:05, 52.31it/s]

tokenising:  91%|█████████ | 2470/2729 [00:54<00:05, 48.80it/s]

tokenising:  91%|█████████ | 2477/2729 [00:54<00:05, 46.57it/s]

tokenising:  91%|█████████ | 2483/2729 [00:54<00:05, 44.94it/s]

tokenising:  91%|█████████ | 2489/2729 [00:54<00:05, 47.25it/s]

tokenising:  91%|█████████▏| 2496/2729 [00:54<00:04, 50.64it/s]

tokenising:  92%|█████████▏| 2503/2729 [00:54<00:04, 53.80it/s]

tokenising:  92%|█████████▏| 2510/2729 [00:55<00:03, 56.19it/s]

tokenising:  92%|█████████▏| 2517/2729 [00:55<00:03, 58.04it/s]

tokenising:  92%|█████████▏| 2524/2729 [00:55<00:03, 59.55it/s]

tokenising:  93%|█████████▎| 2531/2729 [00:55<00:03, 60.20it/s]

tokenising:  93%|█████████▎| 2551/2729 [00:55<00:01, 97.12it/s]

tokenising:  95%|█████████▍| 2586/2729 [00:55<00:00, 163.15it/s]

tokenising:  95%|█████████▌| 2603/2729 [00:55<00:00, 137.03it/s]

tokenising:  96%|█████████▌| 2618/2729 [00:55<00:00, 123.72it/s]

tokenising:  96%|█████████▋| 2632/2729 [00:56<00:00, 114.52it/s]

tokenising:  97%|█████████▋| 2645/2729 [00:56<00:00, 102.41it/s]

tokenising:  97%|█████████▋| 2656/2729 [00:56<00:00, 95.31it/s]

tokenising:  98%|█████████▊| 2666/2729 [00:56<00:00, 90.82it/s]

tokenising:  98%|█████████▊| 2676/2729 [00:56<00:00, 85.41it/s]

tokenising:  98%|█████████▊| 2685/2729 [00:56<00:00, 81.42it/s]

tokenising:  99%|█████████▉| 2696/2729 [00:56<00:00, 86.27it/s]

tokenising:  99%|█████████▉| 2707/2729 [00:56<00:00, 91.92it/s]

tokenising: 100%|█████████▉| 2718/2729 [00:57<00:00, 96.20it/s]

tokenising: 100%|██████████| 2729/2729 [00:57<00:00, 99.70it/s]

tokenising: 100%|██████████| 2729/2729 [00:57<00:00, 47.73it/s]

Examples created : 2,610  |  skipped : 119
LegalBERT training dataset: 2,610 examples

In [8]:
lb_model = AutoModelForQuestionAnswering.from_pretrained(LEGALBERT_NAME)
n_params = sum(p.numel() for p in lb_model.parameters())
print(f"LegalBERT parameters: {n_params:,}")

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 78610.78it/s]

[transformers] BertForQuestionAnswering LOAD REPORT from: nlpaueb/legal-bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
qa_outputs.bias                            | MISSING    |
qa_outputs.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

LegalBERT parameters: 108,893,186

In [9]:
lb_training_args = TrainingArguments(
    output_dir=str(LEGALBERT_OUT),
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    learning_rate=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
    warmup_ratio=0.1,
    logging_steps=25,
    save_strategy="epoch",
    fp16=False,             # fp16 is not supported on MPS (Apple Silicon)
    report_to="none",       # disable W&B / TensorBoard
    dataloader_num_workers=0,  # avoid macOS fork issues
)
print(f"Training on device: {lb_training_args.device}")

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training on device: mps

In [10]:
lb_trainer = Trainer(
    model=lb_model,
    args=lb_training_args,
    train_dataset=lb_train_ds,
)

print(f"Starting LegalBERT fine-tuning...")
print(f"  Examples : {len(lb_train_ds):,}")
print(f"  Epochs   : {NUM_EPOCHS}")
print()

lb_result = lb_trainer.train()

print("\nLegalBERT training complete.")
print(f"  Final loss    : {lb_result.training_loss:.4f}")
print(f"  Steps trained : {lb_result.global_step:,}")
print(f"  Runtime       : {lb_result.metrics['train_runtime']/60:.1f} min")

Starting LegalBERT fine-tuning...
  Examples : 2,610
  Epochs   : 2

/Users/mustafayunus/Desktop/leaseiq-ml/leaseiq-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.19it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.19it/s]

/Users/mustafayunus/Desktop/leaseiq-ml/leaseiq-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.35s/it]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.35s/it]

LegalBERT training complete.
  Final loss    : 2.6795
  Steps trained : 654
  Runtime       : 15.3 min

In [11]:
lb_trainer.save_model(str(LEGALBERT_OUT))
lb_tokenizer.save_pretrained(str(LEGALBERT_OUT))
print(f"LegalBERT model + tokenizer saved to: {LEGALBERT_OUT}")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s]

LegalBERT model + tokenizer saved to: ../models/legalbert-cuad

## Fine-tune DistilBERT (Baseline)

DistilBERT is a knowledge-distilled version of BERT: **40% fewer parameters** and
**60% faster** inference, retaining ~97% of BERT's GLUE performance.

Key difference from LegalBERT: **DistilBERT does not use `token_type_ids`**.
Setting `include_token_type_ids=False` ensures we do not pass that key to the
model, which would cause a forward-pass error.

In [12]:
print(f"Loading DistilBERT tokenizer from: {DISTILBERT_NAME}")
db_tokenizer = AutoTokenizer.from_pretrained(DISTILBERT_NAME)
print("Done.")

Loading DistilBERT tokenizer from: distilbert-base-uncased

Done.

In [13]:
print("Tokenising training sample for DistilBERT...")
db_examples = make_qa_examples(
    train_sample, db_tokenizer,
    max_length=MAX_LENGTH,
    stride=STRIDE,
    include_token_type_ids=False,  # DistilBERT has no token_type_ids
)
db_train_ds = QADataset(db_examples)
print(f"DistilBERT training dataset: {len(db_train_ds):,} examples")

Tokenising training sample for DistilBERT...

tokenising:   0%|          | 0/2729 [00:00<?, ?it/s]

tokenising:   0%|          | 1/2729 [00:00<44:45,  1.02it/s]

tokenising:   0%|          | 4/2729 [00:01<09:48,  4.63it/s]

tokenising:   0%|          | 8/2729 [00:01<04:40,  9.69it/s]

tokenising:   0%|          | 13/2729 [00:01<02:45, 16.44it/s]

tokenising:   1%|          | 18/2729 [00:01<01:57, 23.03it/s]

tokenising:   1%|          | 24/2729 [00:01<01:30, 29.90it/s]

tokenising:   1%|          | 30/2729 [00:01<01:16, 35.32it/s]

tokenising:   1%|▏         | 36/2729 [00:01<01:08, 39.52it/s]

tokenising:   2%|▏         | 42/2729 [00:01<01:03, 42.49it/s]

tokenising:   2%|▏         | 48/2729 [00:02<00:59, 44.92it/s]

tokenising:   2%|▏         | 54/2729 [00:02<00:57, 46.60it/s]

tokenising:   2%|▏         | 60/2729 [00:02<00:55, 47.79it/s]

tokenising:   2%|▏         | 66/2729 [00:02<00:54, 48.65it/s]

tokenising:   3%|▎         | 73/2729 [00:02<00:49, 53.59it/s]

tokenising:   3%|▎         | 85/2729 [00:02<00:37, 71.43it/s]

tokenising:   4%|▎         | 98/2729 [00:02<00:30, 86.12it/s]

tokenising:   4%|▍         | 111/2729 [00:02<00:27, 96.59it/s]

tokenising:   4%|▍         | 121/2729 [00:03<00:40, 64.62it/s]

tokenising:   5%|▍         | 129/2729 [00:03<01:09, 37.52it/s]

tokenising:   5%|▍         | 136/2729 [00:03<01:31, 28.25it/s]

tokenising:   5%|▌         | 141/2729 [00:04<01:44, 24.79it/s]

tokenising:   5%|▌         | 145/2729 [00:04<01:53, 22.68it/s]

tokenising:   5%|▌         | 149/2729 [00:04<02:02, 21.10it/s]

tokenising:   6%|▌         | 152/2729 [00:04<02:09, 19.94it/s]

tokenising:   6%|▌         | 155/2729 [00:05<02:14, 19.13it/s]

tokenising:   6%|▌         | 158/2729 [00:05<02:20, 18.29it/s]

tokenising:   6%|▌         | 160/2729 [00:05<02:24, 17.80it/s]

tokenising:   6%|▌         | 162/2729 [00:05<02:26, 17.48it/s]

tokenising:   6%|▌         | 164/2729 [00:05<02:28, 17.31it/s]

tokenising:   6%|▌         | 166/2729 [00:05<02:30, 17.01it/s]

tokenising:   6%|▌         | 168/2729 [00:05<02:31, 16.88it/s]

tokenising:   6%|▌         | 170/2729 [00:06<02:34, 16.60it/s]

tokenising:   6%|▋         | 172/2729 [00:06<02:42, 15.76it/s]

tokenising:   6%|▋         | 174/2729 [00:06<02:40, 15.88it/s]

tokenising:   6%|▋         | 176/2729 [00:06<02:40, 15.93it/s]

tokenising:   7%|▋         | 178/2729 [00:06<02:38, 16.10it/s]

tokenising:   7%|▋         | 180/2729 [00:06<02:37, 16.15it/s]

tokenising:   7%|▋         | 182/2729 [00:06<02:36, 16.32it/s]

tokenising:   7%|▋         | 184/2729 [00:06<02:36, 16.31it/s]

tokenising:   7%|▋         | 186/2729 [00:07<02:35, 16.36it/s]

tokenising:   7%|▋         | 188/2729 [00:07<02:42, 15.68it/s]

tokenising:   7%|▋         | 191/2729 [00:07<02:23, 17.73it/s]

tokenising:   7%|▋         | 194/2729 [00:07<02:11, 19.32it/s]

tokenising:   7%|▋         | 197/2729 [00:07<02:05, 20.24it/s]

tokenising:   7%|▋         | 200/2729 [00:07<02:02, 20.62it/s]

tokenising:   7%|▋         | 203/2729 [00:07<02:03, 20.44it/s]

tokenising:   8%|▊         | 206/2729 [00:08<02:02, 20.56it/s]

tokenising:   8%|▊         | 209/2729 [00:08<02:00, 20.86it/s]

tokenising:   8%|▊         | 212/2729 [00:08<01:59, 21.09it/s]

tokenising:   8%|▊         | 215/2729 [00:08<01:56, 21.56it/s]

tokenising:   8%|▊         | 218/2729 [00:08<01:54, 21.97it/s]

tokenising:   8%|▊         | 221/2729 [00:08<01:53, 22.10it/s]

tokenising:   8%|▊         | 224/2729 [00:08<01:52, 22.18it/s]

tokenising:   8%|▊         | 227/2729 [00:08<01:51, 22.37it/s]

tokenising:   8%|▊         | 230/2729 [00:09<01:51, 22.50it/s]

tokenising:   9%|▊         | 233/2729 [00:09<01:50, 22.51it/s]

tokenising:   9%|▊         | 236/2729 [00:09<01:50, 22.57it/s]

tokenising:   9%|▉         | 239/2729 [00:09<01:51, 22.37it/s]

tokenising:   9%|▉         | 242/2729 [00:09<01:45, 23.65it/s]

tokenising:   9%|▉         | 250/2729 [00:09<01:07, 36.69it/s]

tokenising:   9%|▉         | 258/2729 [00:09<00:53, 46.34it/s]

tokenising:  10%|▉         | 266/2729 [00:09<00:46, 53.50it/s]

tokenising:  10%|█         | 274/2729 [00:10<00:41, 58.94it/s]

tokenising:  10%|█         | 282/2729 [00:10<00:38, 63.33it/s]

tokenising:  11%|█         | 290/2729 [00:10<00:36, 66.59it/s]

tokenising:  13%|█▎        | 342/2729 [00:10<00:12, 189.71it/s]

tokenising:  13%|█▎        | 362/2729 [00:10<00:13, 181.42it/s]

tokenising:  14%|█▍        | 381/2729 [00:10<00:13, 174.90it/s]

tokenising:  15%|█▍        | 399/2729 [00:10<00:18, 126.84it/s]

tokenising:  15%|█▌        | 414/2729 [00:11<00:21, 105.59it/s]

tokenising:  16%|█▌        | 427/2729 [00:11<00:25, 91.44it/s]

tokenising:  16%|█▌        | 438/2729 [00:11<00:30, 74.39it/s]

tokenising:  16%|█▋        | 447/2729 [00:11<00:37, 60.36it/s]

tokenising:  17%|█▋        | 455/2729 [00:12<00:43, 52.25it/s]

tokenising:  17%|█▋        | 462/2729 [00:12<00:47, 47.43it/s]

tokenising:  17%|█▋        | 468/2729 [00:12<00:50, 44.39it/s]

tokenising:  17%|█▋        | 473/2729 [00:12<00:55, 40.70it/s]

tokenising:  18%|█▊        | 478/2729 [00:12<00:57, 39.04it/s]

tokenising:  18%|█▊        | 482/2729 [00:12<00:59, 38.02it/s]

tokenising:  18%|█▊        | 486/2729 [00:12<01:00, 37.30it/s]

tokenising:  18%|█▊        | 490/2729 [00:13<01:00, 36.74it/s]

tokenising:  18%|█▊        | 494/2729 [00:13<00:59, 37.51it/s]

tokenising:  18%|█▊        | 502/2729 [00:13<00:46, 48.10it/s]

tokenising:  19%|█▊        | 510/2729 [00:13<00:39, 56.32it/s]

tokenising:  19%|█▉        | 518/2729 [00:13<00:35, 62.47it/s]

tokenising:  19%|█▉        | 526/2729 [00:13<00:33, 66.66it/s]

tokenising:  20%|█▉        | 535/2729 [00:13<00:30, 71.25it/s]

tokenising:  20%|█▉        | 544/2729 [00:13<00:29, 75.17it/s]

tokenising:  20%|██        | 558/2729 [00:13<00:23, 93.00it/s]

tokenising:  21%|██        | 571/2729 [00:14<00:21, 101.84it/s]

tokenising:  21%|██▏       | 585/2729 [00:14<00:19, 111.31it/s]

tokenising:  22%|██▏       | 597/2729 [00:14<00:19, 111.30it/s]

tokenising:  22%|██▏       | 609/2729 [00:16<02:11, 16.18it/s]

tokenising:  23%|██▎       | 617/2729 [00:16<01:49, 19.21it/s]

tokenising:  23%|██▎       | 625/2729 [00:16<01:31, 22.90it/s]

tokenising:  23%|██▎       | 632/2729 [00:16<01:18, 26.80it/s]

tokenising:  23%|██▎       | 639/2729 [00:16<01:07, 30.93it/s]

tokenising:  24%|██▎       | 646/2729 [00:17<00:57, 35.99it/s]

tokenising:  24%|██▍       | 662/2729 [00:17<00:37, 55.83it/s]

tokenising:  25%|██▍       | 678/2729 [00:17<00:27, 74.55it/s]

tokenising:  25%|██▌       | 691/2729 [00:17<00:24, 82.14it/s]

tokenising:  26%|██▌       | 702/2729 [00:17<00:33, 60.39it/s]

tokenising:  26%|██▌       | 711/2729 [00:17<00:40, 50.18it/s]

tokenising:  26%|██▋       | 719/2729 [00:18<00:43, 46.27it/s]

tokenising:  27%|██▋       | 726/2729 [00:18<00:45, 43.75it/s]

tokenising:  27%|██▋       | 732/2729 [00:18<00:47, 41.99it/s]

tokenising:  27%|██▋       | 737/2729 [00:18<00:48, 41.01it/s]

tokenising:  27%|██▋       | 742/2729 [00:18<00:49, 40.03it/s]

tokenising:  27%|██▋       | 748/2729 [00:18<00:45, 43.87it/s]

tokenising:  28%|██▊       | 762/2729 [00:19<00:30, 65.08it/s]

tokenising:  28%|██▊       | 775/2729 [00:19<00:24, 80.63it/s]

tokenising:  29%|██▉       | 789/2729 [00:19<00:20, 95.28it/s]

tokenising:  29%|██▉       | 800/2729 [00:20<01:12, 26.43it/s]

tokenising:  30%|██▉       | 808/2729 [00:21<01:59, 16.10it/s]

tokenising:  30%|██▉       | 814/2729 [00:22<02:33, 12.45it/s]

tokenising:  30%|███       | 819/2729 [00:23<02:58, 10.68it/s]

tokenising:  30%|███       | 823/2729 [00:23<03:13,  9.85it/s]

tokenising:  30%|███       | 826/2729 [00:24<03:25,  9.24it/s]

tokenising:  30%|███       | 828/2729 [00:24<03:34,  8.85it/s]

tokenising:  30%|███       | 830/2729 [00:24<03:42,  8.52it/s]

tokenising:  30%|███       | 832/2729 [00:24<03:52,  8.18it/s]

tokenising:  31%|███       | 834/2729 [00:25<03:57,  7.96it/s]

tokenising:  31%|███       | 835/2729 [00:25<04:00,  7.88it/s]

tokenising:  31%|███       | 836/2729 [00:25<04:03,  7.77it/s]

tokenising:  31%|███       | 837/2729 [00:25<04:06,  7.68it/s]

tokenising:  31%|███       | 838/2729 [00:25<04:11,  7.51it/s]

tokenising:  31%|███       | 839/2729 [00:25<04:21,  7.23it/s]

tokenising:  31%|███       | 840/2729 [00:26<04:20,  7.24it/s]

tokenising:  31%|███       | 841/2729 [00:26<04:21,  7.22it/s]

tokenising:  31%|███       | 842/2729 [00:26<04:26,  7.09it/s]

tokenising:  31%|███       | 843/2729 [00:26<04:27,  7.05it/s]

tokenising:  31%|███       | 844/2729 [00:26<04:27,  7.06it/s]

tokenising:  31%|███       | 845/2729 [00:26<04:26,  7.07it/s]

tokenising:  31%|███       | 846/2729 [00:26<04:27,  7.05it/s]

tokenising:  31%|███       | 847/2729 [00:27<04:26,  7.06it/s]

tokenising:  31%|███       | 848/2729 [00:27<04:24,  7.11it/s]

tokenising:  31%|███       | 849/2729 [00:27<04:20,  7.21it/s]

tokenising:  31%|███       | 850/2729 [00:27<04:31,  6.92it/s]

tokenising:  31%|███       | 851/2729 [00:27<04:25,  7.07it/s]

tokenising:  31%|███       | 852/2729 [00:27<04:25,  7.06it/s]

tokenising:  31%|███▏      | 853/2729 [00:27<04:21,  7.17it/s]

tokenising:  31%|███▏      | 854/2729 [00:28<04:19,  7.23it/s]

tokenising:  31%|███▏      | 855/2729 [00:28<04:17,  7.29it/s]

tokenising:  31%|███▏      | 856/2729 [00:28<04:17,  7.27it/s]

tokenising:  31%|███▏      | 857/2729 [00:28<04:34,  6.81it/s]

tokenising:  31%|███▏      | 858/2729 [00:28<04:39,  6.70it/s]

tokenising:  31%|███▏      | 859/2729 [00:28<04:30,  6.90it/s]

tokenising:  32%|███▏      | 860/2729 [00:28<04:24,  7.08it/s]

tokenising:  32%|███▏      | 861/2729 [00:29<04:23,  7.08it/s]

tokenising:  32%|███▏      | 862/2729 [00:29<04:19,  7.20it/s]

tokenising:  32%|███▏      | 863/2729 [00:29<04:15,  7.32it/s]

tokenising:  32%|███▏      | 864/2729 [00:29<04:16,  7.27it/s]

tokenising:  32%|███▏      | 865/2729 [00:29<04:21,  7.12it/s]

tokenising:  32%|███▏      | 866/2729 [00:29<04:22,  7.10it/s]

tokenising:  32%|███▏      | 867/2729 [00:29<04:25,  7.02it/s]

tokenising:  32%|███▏      | 868/2729 [00:30<04:20,  7.14it/s]

tokenising:  32%|███▏      | 869/2729 [00:30<04:19,  7.17it/s]

tokenising:  32%|███▏      | 870/2729 [00:30<04:19,  7.16it/s]

tokenising:  32%|███▏      | 871/2729 [00:30<04:22,  7.07it/s]

tokenising:  32%|███▏      | 872/2729 [00:30<04:25,  7.00it/s]

tokenising:  32%|███▏      | 873/2729 [00:30<04:23,  7.03it/s]

tokenising:  32%|███▏      | 874/2729 [00:30<04:22,  7.06it/s]

tokenising:  32%|███▏      | 875/2729 [00:31<04:20,  7.11it/s]

tokenising:  32%|███▏      | 876/2729 [00:31<06:17,  4.91it/s]

tokenising:  32%|███▏      | 877/2729 [00:31<05:53,  5.24it/s]

tokenising:  32%|███▏      | 878/2729 [00:31<05:30,  5.60it/s]

tokenising:  32%|███▏      | 879/2729 [00:31<05:13,  5.91it/s]

tokenising:  32%|███▏      | 880/2729 [00:31<05:05,  6.06it/s]

tokenising:  32%|███▏      | 881/2729 [00:32<04:51,  6.33it/s]

tokenising:  33%|███▎      | 888/2729 [00:32<01:34, 19.55it/s]

tokenising:  33%|███▎      | 896/2729 [00:32<00:56, 32.32it/s]

tokenising:  33%|███▎      | 903/2729 [00:32<00:44, 40.73it/s]

tokenising:  33%|███▎      | 909/2729 [00:32<00:40, 45.15it/s]

tokenising:  34%|███▎      | 916/2729 [00:32<00:35, 50.44it/s]

tokenising:  34%|███▍      | 923/2729 [00:32<00:32, 55.69it/s]

tokenising:  34%|███▍      | 931/2729 [00:32<00:29, 61.54it/s]

tokenising:  34%|███▍      | 939/2729 [00:32<00:27, 65.71it/s]

tokenising:  35%|███▍      | 947/2729 [00:33<00:25, 68.57it/s]

tokenising:  35%|███▍      | 955/2729 [00:33<00:24, 71.55it/s]

tokenising:  35%|███▌      | 963/2729 [00:33<00:23, 73.83it/s]

tokenising:  36%|███▌      | 971/2729 [00:33<00:23, 75.46it/s]

tokenising:  36%|███▌      | 981/2729 [00:33<00:21, 81.74it/s]

tokenising:  36%|███▋      | 995/2729 [00:33<00:17, 98.63it/s]

tokenising:  37%|███▋      | 1009/2729 [00:33<00:15, 110.43it/s]

tokenising:  38%|███▊      | 1024/2729 [00:33<00:14, 119.68it/s]

tokenising:  38%|███▊      | 1038/2729 [00:33<00:13, 123.28it/s]

tokenising:  39%|███▊      | 1051/2729 [00:34<00:14, 116.58it/s]

tokenising:  39%|███▉      | 1063/2729 [00:34<00:14, 112.50it/s]

tokenising:  39%|███▉      | 1075/2729 [00:34<00:14, 110.46it/s]

tokenising:  40%|████      | 1097/2729 [00:34<00:11, 140.54it/s]

tokenising:  42%|████▏     | 1137/2729 [00:34<00:08, 198.72it/s]

tokenising:  42%|████▏     | 1157/2729 [00:35<00:18, 83.77it/s]

tokenising:  43%|████▎     | 1172/2729 [00:35<00:24, 64.07it/s]

tokenising:  43%|████▎     | 1184/2729 [00:35<00:28, 55.15it/s]

tokenising:  44%|████▎     | 1193/2729 [00:36<00:28, 53.68it/s]

tokenising:  44%|████▍     | 1207/2729 [00:36<00:23, 64.80it/s]

tokenising:  45%|████▍     | 1220/2729 [00:36<00:20, 74.62it/s]

tokenising:  45%|████▌     | 1233/2729 [00:36<00:17, 83.61it/s]

tokenising:  46%|████▌     | 1246/2729 [00:36<00:15, 92.83it/s]

tokenising:  46%|████▌     | 1260/2729 [00:36<00:14, 102.44it/s]

tokenising:  47%|████▋     | 1273/2729 [00:36<00:13, 108.87it/s]

tokenising:  47%|████▋     | 1286/2729 [00:36<00:12, 113.64it/s]

tokenising:  48%|████▊     | 1299/2729 [00:36<00:12, 116.38it/s]

tokenising:  48%|████▊     | 1312/2729 [00:37<00:12, 112.98it/s]

tokenising:  49%|████▊     | 1324/2729 [00:37<00:12, 112.51it/s]

tokenising:  49%|████▉     | 1336/2729 [00:37<00:12, 111.97it/s]

tokenising:  49%|████▉     | 1348/2729 [00:37<00:12, 111.81it/s]

tokenising:  50%|████▉     | 1360/2729 [00:37<00:12, 110.00it/s]

tokenising:  50%|█████     | 1372/2729 [00:37<00:12, 106.54it/s]

tokenising:  51%|█████     | 1383/2729 [00:37<00:13, 101.18it/s]

tokenising:  51%|█████     | 1394/2729 [00:37<00:13, 96.16it/s]

tokenising:  51%|█████▏    | 1404/2729 [00:37<00:14, 90.09it/s]

tokenising:  52%|█████▏    | 1414/2729 [00:38<00:18, 71.50it/s]

tokenising:  52%|█████▏    | 1422/2729 [00:38<00:20, 64.64it/s]

tokenising:  52%|█████▏    | 1429/2729 [00:38<00:21, 60.35it/s]

tokenising:  53%|█████▎    | 1436/2729 [00:38<00:22, 57.15it/s]

tokenising:  53%|█████▎    | 1442/2729 [00:38<00:23, 55.03it/s]

tokenising:  53%|█████▎    | 1448/2729 [00:38<00:23, 53.69it/s]

tokenising:  53%|█████▎    | 1454/2729 [00:38<00:24, 52.58it/s]

tokenising:  53%|█████▎    | 1460/2729 [00:39<00:24, 51.80it/s]

tokenising:  54%|█████▎    | 1466/2729 [00:39<00:24, 51.24it/s]

tokenising:  55%|█████▍    | 1498/2729 [00:39<00:10, 119.50it/s]

tokenising:  55%|█████▌    | 1514/2729 [00:39<00:09, 125.46it/s]

tokenising:  56%|█████▌    | 1528/2729 [00:40<00:22, 52.34it/s]

tokenising:  56%|█████▋    | 1539/2729 [00:40<00:30, 38.67it/s]

tokenising:  57%|█████▋    | 1547/2729 [00:40<00:35, 33.00it/s]

tokenising:  57%|█████▋    | 1553/2729 [00:41<00:39, 30.07it/s]

tokenising:  57%|█████▋    | 1558/2729 [00:41<00:41, 28.21it/s]

tokenising:  57%|█████▋    | 1563/2729 [00:41<00:44, 26.06it/s]

tokenising:  57%|█████▋    | 1567/2729 [00:41<00:47, 24.63it/s]

tokenising:  58%|█████▊    | 1570/2729 [00:42<00:48, 23.79it/s]

tokenising:  58%|█████▊    | 1573/2729 [00:42<00:50, 22.73it/s]

tokenising:  58%|█████▊    | 1576/2729 [00:42<00:49, 23.43it/s]

tokenising:  58%|█████▊    | 1583/2729 [00:42<00:35, 32.13it/s]

tokenising:  58%|█████▊    | 1590/2729 [00:42<00:28, 39.91it/s]

tokenising:  59%|█████▊    | 1597/2729 [00:42<00:24, 46.59it/s]

tokenising:  59%|█████▉    | 1604/2729 [00:42<00:21, 52.37it/s]

tokenising:  59%|█████▉    | 1611/2729 [00:42<00:19, 56.90it/s]

tokenising:  59%|█████▉    | 1618/2729 [00:42<00:18, 60.12it/s]

tokenising:  60%|█████▉    | 1625/2729 [00:43<00:17, 62.60it/s]

tokenising:  60%|█████▉    | 1632/2729 [00:43<00:25, 43.31it/s]

tokenising:  60%|██████    | 1638/2729 [00:43<00:29, 36.37it/s]

tokenising:  60%|██████    | 1643/2729 [00:43<00:32, 33.15it/s]

tokenising:  60%|██████    | 1647/2729 [00:43<00:34, 31.23it/s]

tokenising:  60%|██████    | 1651/2729 [00:44<00:38, 27.99it/s]

tokenising:  61%|██████    | 1655/2729 [00:44<00:39, 27.32it/s]

tokenising:  61%|██████    | 1658/2729 [00:44<00:39, 26.94it/s]

tokenising:  61%|██████    | 1661/2729 [00:44<00:40, 26.67it/s]

tokenising:  61%|██████    | 1664/2729 [00:44<00:40, 26.40it/s]

tokenising:  61%|██████    | 1667/2729 [00:44<00:40, 26.31it/s]

tokenising:  61%|██████    | 1670/2729 [00:44<00:40, 26.27it/s]

tokenising:  61%|██████▏   | 1673/2729 [00:44<00:40, 26.03it/s]

tokenising:  61%|██████▏   | 1676/2729 [00:45<00:40, 25.98it/s]

tokenising:  62%|██████▏   | 1679/2729 [00:45<00:40, 26.11it/s]

tokenising:  62%|██████▏   | 1682/2729 [00:45<00:40, 26.13it/s]

tokenising:  62%|██████▏   | 1685/2729 [00:45<00:51, 20.30it/s]

tokenising:  62%|██████▏   | 1688/2729 [00:45<00:47, 21.75it/s]

tokenising:  62%|██████▏   | 1691/2729 [00:45<00:45, 22.94it/s]

tokenising:  62%|██████▏   | 1694/2729 [00:45<00:43, 23.88it/s]

tokenising:  62%|██████▏   | 1697/2729 [00:45<00:42, 24.28it/s]

tokenising:  62%|██████▏   | 1700/2729 [00:46<00:41, 24.67it/s]

tokenising:  62%|██████▏   | 1703/2729 [00:46<00:41, 24.65it/s]

tokenising:  63%|██████▎   | 1706/2729 [00:46<00:40, 25.24it/s]

tokenising:  63%|██████▎   | 1709/2729 [00:46<00:39, 25.70it/s]

tokenising:  63%|██████▎   | 1712/2729 [00:46<00:39, 25.94it/s]

tokenising:  63%|██████▎   | 1715/2729 [00:46<00:39, 25.91it/s]

tokenising:  63%|██████▎   | 1718/2729 [00:46<00:39, 25.74it/s]

tokenising:  63%|██████▎   | 1721/2729 [00:46<00:39, 25.52it/s]

tokenising:  63%|██████▎   | 1724/2729 [00:47<00:39, 25.75it/s]

tokenising:  63%|██████▎   | 1727/2729 [00:47<00:38, 25.92it/s]

tokenising:  63%|██████▎   | 1731/2729 [00:47<00:34, 28.79it/s]

tokenising:  64%|██████▎   | 1735/2729 [00:47<00:32, 30.79it/s]

tokenising:  64%|██████▎   | 1739/2729 [00:47<00:30, 32.27it/s]

tokenising:  64%|██████▍   | 1743/2729 [00:47<00:29, 33.60it/s]

tokenising:  64%|██████▍   | 1747/2729 [00:47<00:28, 34.55it/s]

tokenising:  64%|██████▍   | 1751/2729 [00:47<00:27, 35.25it/s]

tokenising:  64%|██████▍   | 1755/2729 [00:47<00:27, 35.60it/s]

tokenising:  64%|██████▍   | 1759/2729 [00:48<00:27, 35.89it/s]

tokenising:  65%|██████▍   | 1763/2729 [00:48<00:26, 36.04it/s]

tokenising:  65%|██████▍   | 1767/2729 [00:48<00:26, 36.19it/s]

tokenising:  65%|██████▍   | 1771/2729 [00:48<00:26, 36.58it/s]

tokenising:  65%|██████▌   | 1775/2729 [00:48<00:26, 36.41it/s]

tokenising:  65%|██████▌   | 1779/2729 [00:48<00:26, 36.10it/s]

tokenising:  65%|██████▌   | 1783/2729 [00:48<00:26, 36.35it/s]

tokenising:  65%|██████▌   | 1787/2729 [00:48<00:25, 36.55it/s]

tokenising:  66%|██████▌   | 1791/2729 [00:48<00:25, 36.66it/s]

tokenising:  66%|██████▌   | 1795/2729 [00:49<00:25, 36.58it/s]

tokenising:  66%|██████▌   | 1799/2729 [00:49<00:25, 36.51it/s]

tokenising:  66%|██████▌   | 1804/2729 [00:49<00:23, 38.91it/s]

tokenising:  66%|██████▋   | 1811/2729 [00:49<00:19, 47.52it/s]

tokenising:  67%|██████▋   | 1819/2729 [00:49<00:16, 54.55it/s]

tokenising:  67%|██████▋   | 1827/2729 [00:49<00:15, 59.40it/s]

tokenising:  67%|██████▋   | 1835/2729 [00:49<00:14, 62.92it/s]

tokenising:  67%|██████▋   | 1842/2729 [00:49<00:13, 64.83it/s]

tokenising:  68%|██████▊   | 1850/2729 [00:49<00:13, 66.69it/s]

tokenising:  68%|██████▊   | 1857/2729 [00:50<00:16, 51.89it/s]

tokenising:  68%|██████▊   | 1863/2729 [00:50<00:20, 42.26it/s]

tokenising:  68%|██████▊   | 1868/2729 [00:50<00:22, 37.58it/s]

tokenising:  69%|██████▊   | 1873/2729 [00:50<00:24, 34.32it/s]

tokenising:  69%|██████▉   | 1877/2729 [00:50<00:26, 32.37it/s]

tokenising:  69%|██████▉   | 1881/2729 [00:50<00:27, 30.79it/s]

tokenising:  69%|██████▉   | 1885/2729 [00:51<00:28, 29.49it/s]

tokenising:  69%|██████▉   | 1889/2729 [00:51<00:28, 29.00it/s]

tokenising:  69%|██████▉   | 1892/2729 [00:51<00:29, 28.76it/s]

tokenising:  69%|██████▉   | 1895/2729 [00:51<00:29, 28.51it/s]

tokenising:  70%|██████▉   | 1898/2729 [00:51<00:29, 28.20it/s]

tokenising:  70%|██████▉   | 1901/2729 [00:51<00:30, 27.49it/s]

tokenising:  70%|██████▉   | 1904/2729 [00:51<00:30, 27.33it/s]

tokenising:  70%|██████▉   | 1907/2729 [00:51<00:30, 27.33it/s]

tokenising:  70%|██████▉   | 1910/2729 [00:52<00:29, 27.33it/s]

tokenising:  70%|███████   | 1913/2729 [00:52<00:29, 27.47it/s]

tokenising:  70%|███████   | 1916/2729 [00:52<00:29, 27.53it/s]

tokenising:  70%|███████   | 1919/2729 [00:52<00:29, 27.43it/s]

tokenising:  70%|███████   | 1922/2729 [00:52<00:29, 27.44it/s]

tokenising:  71%|███████   | 1926/2729 [00:52<00:26, 30.43it/s]

tokenising:  71%|███████   | 1933/2729 [00:52<00:19, 40.45it/s]

tokenising:  71%|███████   | 1940/2729 [00:52<00:16, 47.38it/s]

tokenising:  71%|███████▏  | 1947/2729 [00:52<00:14, 52.31it/s]

tokenising:  72%|███████▏  | 1954/2729 [00:53<00:13, 55.36it/s]

tokenising:  72%|███████▏  | 1961/2729 [00:53<00:13, 58.01it/s]

tokenising:  72%|███████▏  | 1968/2729 [00:53<00:12, 59.55it/s]

tokenising:  73%|███████▎  | 1980/2729 [00:53<00:09, 76.32it/s]

tokenising:  73%|███████▎  | 1998/2729 [00:53<00:06, 104.64it/s]

tokenising:  74%|███████▍  | 2015/2729 [00:53<00:05, 123.19it/s]

tokenising:  74%|███████▍  | 2028/2729 [00:53<00:06, 109.84it/s]

tokenising:  75%|███████▍  | 2040/2729 [00:53<00:07, 94.82it/s]

tokenising:  75%|███████▌  | 2051/2729 [00:54<00:07, 86.34it/s]

tokenising:  76%|███████▌  | 2061/2729 [00:54<00:08, 81.94it/s]

tokenising:  76%|███████▌  | 2070/2729 [00:54<00:08, 78.63it/s]

tokenising:  76%|███████▌  | 2079/2729 [00:54<00:08, 75.06it/s]

tokenising:  76%|███████▋  | 2087/2729 [00:54<00:09, 70.24it/s]

tokenising:  77%|███████▋  | 2095/2729 [00:54<00:09, 67.02it/s]

tokenising:  77%|███████▋  | 2102/2729 [00:54<00:09, 64.92it/s]

tokenising:  77%|███████▋  | 2109/2729 [00:54<00:09, 63.40it/s]

tokenising:  78%|███████▊  | 2116/2729 [00:55<00:09, 62.20it/s]

tokenising:  78%|███████▊  | 2123/2729 [00:55<00:09, 61.39it/s]

tokenising:  79%|███████▊  | 2143/2729 [00:55<00:06, 97.14it/s]

tokenising:  79%|███████▉  | 2167/2729 [00:55<00:04, 134.45it/s]

tokenising:  80%|███████▉  | 2182/2729 [00:55<00:05, 102.19it/s]

tokenising:  80%|████████  | 2194/2729 [00:55<00:06, 83.84it/s]

tokenising:  81%|████████  | 2204/2729 [00:56<00:07, 74.72it/s]

tokenising:  81%|████████  | 2213/2729 [00:56<00:07, 68.92it/s]

tokenising:  81%|████████▏ | 2221/2729 [00:56<00:07, 66.78it/s]

tokenising:  82%|████████▏ | 2229/2729 [00:56<00:07, 66.43it/s]

tokenising:  82%|████████▏ | 2236/2729 [00:56<00:07, 66.40it/s]

tokenising:  82%|████████▏ | 2243/2729 [00:56<00:07, 66.26it/s]

tokenising:  82%|████████▏ | 2250/2729 [00:56<00:07, 66.19it/s]

tokenising:  83%|████████▎ | 2257/2729 [00:56<00:07, 65.99it/s]

tokenising:  83%|████████▎ | 2264/2729 [00:56<00:07, 65.60it/s]

tokenising:  83%|████████▎ | 2271/2729 [00:57<00:07, 65.40it/s]

tokenising:  83%|████████▎ | 2278/2729 [00:57<00:06, 65.26it/s]

tokenising:  84%|████████▍ | 2294/2729 [00:57<00:04, 91.31it/s]

tokenising:  85%|████████▍ | 2318/2729 [00:57<00:03, 132.14it/s]

tokenising:  85%|████████▌ | 2333/2729 [00:57<00:02, 137.01it/s]

tokenising:  86%|████████▌ | 2347/2729 [00:57<00:03, 116.24it/s]

tokenising:  86%|████████▋ | 2360/2729 [00:57<00:03, 105.54it/s]

tokenising:  87%|████████▋ | 2372/2729 [00:57<00:03, 99.05it/s]

tokenising:  87%|████████▋ | 2383/2729 [00:58<00:04, 84.67it/s]

tokenising:  88%|████████▊ | 2407/2729 [00:58<00:02, 118.86it/s]

tokenising:  89%|████████▉ | 2424/2729 [00:58<00:02, 127.23it/s]

tokenising:  89%|████████▉ | 2438/2729 [00:58<00:03, 79.65it/s]

tokenising:  90%|████████▉ | 2449/2729 [00:58<00:04, 64.13it/s]

tokenising:  90%|█████████ | 2458/2729 [00:59<00:04, 56.53it/s]

tokenising:  90%|█████████ | 2466/2729 [00:59<00:05, 51.62it/s]

tokenising:  91%|█████████ | 2473/2729 [00:59<00:05, 48.32it/s]

tokenising:  91%|█████████ | 2479/2729 [00:59<00:05, 45.98it/s]

tokenising:  91%|█████████ | 2485/2729 [00:59<00:05, 44.79it/s]

tokenising:  91%|█████████▏| 2492/2729 [01:00<00:04, 48.77it/s]

tokenising:  92%|█████████▏| 2499/2729 [01:00<00:04, 52.17it/s]

tokenising:  92%|█████████▏| 2506/2729 [01:00<00:04, 54.90it/s]

tokenising:  92%|█████████▏| 2513/2729 [01:00<00:03, 56.87it/s]

tokenising:  92%|█████████▏| 2520/2729 [01:00<00:03, 58.49it/s]

tokenising:  93%|█████████▎| 2527/2729 [01:00<00:03, 59.67it/s]

tokenising:  93%|█████████▎| 2534/2729 [01:00<00:03, 60.35it/s]

tokenising:  95%|█████████▍| 2581/2729 [01:00<00:00, 165.61it/s]

tokenising:  95%|█████████▌| 2599/2729 [01:00<00:00, 134.50it/s]

tokenising:  96%|█████████▌| 2614/2729 [01:01<00:00, 120.50it/s]

tokenising:  96%|█████████▋| 2628/2729 [01:01<00:00, 111.76it/s]

tokenising:  97%|█████████▋| 2640/2729 [01:01<00:00, 102.53it/s]

tokenising:  97%|█████████▋| 2651/2729 [01:01<00:00, 95.23it/s]

tokenising:  98%|█████████▊| 2661/2729 [01:01<00:00, 90.26it/s]

tokenising:  98%|█████████▊| 2671/2729 [01:01<00:00, 85.31it/s]

tokenising:  98%|█████████▊| 2680/2729 [01:01<00:00, 83.00it/s]

tokenising:  99%|█████████▊| 2691/2729 [01:02<00:00, 88.15it/s]

tokenising:  99%|█████████▉| 2702/2729 [01:02<00:00, 92.52it/s]

tokenising:  99%|█████████▉| 2713/2729 [01:02<00:00, 95.73it/s]

tokenising: 100%|█████████▉| 2724/2729 [01:02<00:00, 98.12it/s]

tokenising: 100%|██████████| 2729/2729 [01:02<00:00, 43.70it/s]

Examples created : 2,605  |  skipped : 124
DistilBERT training dataset: 2,605 examples

In [14]:
db_model = AutoModelForQuestionAnswering.from_pretrained(DISTILBERT_NAME)
n_params = sum(p.numel() for p in db_model.parameters())
print(f"DistilBERT parameters: {n_params:,}")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 8200.65it/s]

[transformers] DistilBertForQuestionAnswering LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
qa_outputs.bias         | MISSING    |
qa_outputs.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

DistilBERT parameters: 66,364,418

In [15]:
db_training_args = TrainingArguments(
    output_dir=str(DISTILBERT_OUT),
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    learning_rate=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
    warmup_ratio=0.1,
    logging_steps=25,
    save_strategy="epoch",
    fp16=False,
    report_to="none",
    dataloader_num_workers=0,
)

db_trainer = Trainer(
    model=db_model,
    args=db_training_args,
    train_dataset=db_train_ds,
)

print(f"Starting DistilBERT fine-tuning...")
print(f"  Examples : {len(db_train_ds):,}")
print(f"  Epochs   : {NUM_EPOCHS}")
print()

db_result = db_trainer.train()

print("\nDistilBERT training complete.")
print(f"  Final loss    : {db_result.training_loss:.4f}")
print(f"  Steps trained : {db_result.global_step:,}")
print(f"  Runtime       : {db_result.metrics['train_runtime']/60:.1f} min")

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Starting DistilBERT fine-tuning...
  Examples : 2,605
  Epochs   : 2

/Users/mustafayunus/Desktop/leaseiq-ml/leaseiq-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.12it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.11it/s]

/Users/mustafayunus/Desktop/leaseiq-ml/leaseiq-env/lib/python3.12/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s]

DistilBERT training complete.
  Final loss    : 2.8262
  Steps trained : 652
  Runtime       : 7.3 min

In [16]:
db_trainer.save_model(str(DISTILBERT_OUT))
db_tokenizer.save_pretrained(str(DISTILBERT_OUT))
print(f"DistilBERT model + tokenizer saved to: {DISTILBERT_OUT}")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]

DistilBERT model + tokenizer saved to: ../models/distilbert-cuad

## Training Summary

In [17]:
summary = pd.DataFrame({
    "Model": ["LegalBERT", "DistilBERT (baseline)"],
    "HuggingFace ID": [LEGALBERT_NAME, DISTILBERT_NAME],
    "Parameters": [
        f"{sum(p.numel() for p in lb_model.parameters()):,}",
        f"{sum(p.numel() for p in db_model.parameters()):,}",
    ],
    "Train examples": [len(lb_train_ds), len(db_train_ds)],
    "Epochs": [NUM_EPOCHS, NUM_EPOCHS],
    "Batch size": [BATCH_SIZE, BATCH_SIZE],
    "Final train loss": [
        round(lb_result.training_loss, 4),
        round(db_result.training_loss, 4),
    ],
    "Runtime (min)": [
        round(lb_result.metrics["train_runtime"] / 60, 1),
        round(db_result.metrics["train_runtime"] / 60, 1),
    ],
    "Saved to": [str(LEGALBERT_OUT), str(DISTILBERT_OUT)],
}).set_index("Model")

print("=== Training Summary ===")
print(summary.to_string())

=== Training Summary ===

                                        HuggingFace ID   Parameters  Train examples  Epochs  Batch size  Final train loss  Runtime (min)                   Saved to
Model
LegalBERT              nlpaueb/legal-bert-base-uncased  108,893,186            2610       2           8            2.6795           15.3   ../models/legalbert-cuad
DistilBERT (baseline)          distilbert-base-uncased   66,364,418            2605       2           8            2.8262            7.3  ../models/distilbert-cuad